# Generated by Django 4.2.6 on 2023-11-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.BigIntegerField(verbose_name='Идентификатор объекта')),
                ('obj_type', models.CharField(choices=[('doc', 'Документ'), ('news', 'Новость'), ('event', 'Мероприятие/событие')], max_length=5, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очереди',
            },
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('obj_id', 'obj_type'), name='unique_obj_id_type'),
        ),
    ]
