# Generated by Django 4.2.6 on 2023-11-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(choices=[('doc', 'Документ'), ('news', 'Новость'), ('event', 'Мероприятие/событие'), ('scientist', 'Учёный'), ('grant', 'Грант')], max_length=10, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очереди',
            },
        ),
    ]
