# Generated by Django 4.2.6 on 2023-12-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('id', 'obj_type'), name='unique_id_type_obj'),
        ),
    ]
