# Generated by Django 4.2.6 on 2023-11-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='obj_type',
            field=models.CharField(choices=[('doc', 'Документ'), ('news', 'Новость'), ('event', 'Мероприятие/событие'), ('scientist', 'Учёный'), ('grant', 'Грант')], max_length=10, verbose_name='Тип объекта'),
        ),
    ]
