# Generated by Django 4.2.6 on 2023-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0002_queue_unique_id_type_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='obj_type',
            field=models.CharField(choices=[('doc', 'Документ'), ('news', 'Новость'), ('event', 'Мероприятие/событие'), ('scientist', 'Учёный')], max_length=10, verbose_name='Тип объекта'),
        ),
    ]
