# Generated by Django 4.2.6 on 2023-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0003_alter_queue_obj_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='queue',
            name='unique_id_type_obj',
        ),
        migrations.AddField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('pub', 'Публикация'), ('chg', 'Изменение'), ('del', 'Удаление')], default='Публикация', max_length=10, verbose_name='Статус запрашиваемого объекта'),
        ),
    ]
