# Generated by Django 4.2.6 on 2023-11-30 04:58

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('category', models.CharField(default='', max_length=300, verbose_name='Категория (каталог) документа')),
                ('path', models.FileField(upload_to=documents.models.Doc._img_dir_path, verbose_name='Путь до документа')),
            ],
        ),
    ]
