# Generated by Django 4.2.6 on 2024-01-31 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_doc_category'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='doc',
        #     name='category',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.category'),
        # ),
    ]
