# Generated by Django 4.2.6 on 2023-12-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_category_remove_doc_category_doc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.category'),
        ),
    ]
