# Generated by Django 4.2.6 on 2024-01-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='documents.doc', verbose_name='id документа')),
                ('description', models.TextField(verbose_name='Описание документа')),
                ('on_changed', models.BigIntegerField(null=True, verbose_name='ID заменяемой записи')),
            ],
        ),
    ]
