# Generated by Django 4.2.6 on 2023-12-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основной текст')),
            ],
        ),
        migrations.CreateModel(
            name='BlockForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.TextField(verbose_name='хммммммммммммммммммммммммммммммммммммммм')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.TextField(verbose_name='пжпжпжпжппжпжпжпжпжпжппжпжпжпжпжпжпжпжпж')),
            ],
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border_color', models.CharField(max_length=50, verbose_name='Цвет границы')),
                ('fill_color', models.CharField(max_length=50, verbose_name='Цвет заливки')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHC.blockform')),
            ],
        ),
        migrations.CreateModel(
            name='BlockLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHC.block')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.doc')),
            ],
        ),
        migrations.CreateModel(
            name='BlockConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('connect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHC.connectiontype')),
                ('main_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_block', to='SHC.block', verbose_name='Главный блок')),
                ('side_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_block', to='SHC.block', verbose_name='Побочный блок')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHC.blocktype'),
        ),
    ]
