# Generated by Django 4.2.6 on 2023-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHC', '0002_doc_remove_blockconnection_connect_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='on_changed',
            field=models.BigIntegerField(null=True, verbose_name='ID заменяемой записи'),
        ),
    ]
