# Generated by Django 4.2.6 on 2023-11-30 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue')),
                ('name', models.CharField(max_length=300, verbose_name='Название гранта')),
                ('description', models.TextField(null=True, verbose_name='Описание гранта')),
                ('end_doc_date', models.DateTimeField(null=True, verbose_name='Дата окончания приёма заявок')),
                ('end_result_date', models.DateTimeField(null=True, verbose_name='Дата подведения итогов')),
                ('criteria', models.TextField(verbose_name='Критерии к участникам')),
                ('link', models.URLField(verbose_name='Ссылка на страницу с грантом')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название института')),
                ('description', models.TextField(verbose_name='Информация об институте')),
                ('structure', models.TextField(verbose_name='Структура института')),
                ('link', models.URLField(verbose_name='Ссылка на сайт института')),
            ],
        ),
        migrations.CreateModel(
            name='ScientistInfo',
            fields=[
                ('scientist', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue')),
                ('name', models.CharField(max_length=200, verbose_name='Имя учёного')),
                ('lab', models.CharField(max_length=300, verbose_name='Лаборатория')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('degree', models.CharField(max_length=200, null=True, verbose_name='Учёная степень')),
                ('teaching_info', models.TextField(null=True, verbose_name='Информация о преподавании')),
                ('scientific_interests', models.TextField(verbose_name='Сфера научных интересов')),
                ('achievements', models.TextField(null=True, verbose_name='Достижения')),
                ('future_plans', models.TextField(null=True, verbose_name='Планы на будущее')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.institute')),
            ],
        ),
        migrations.CreateModel(
            name='ScientistPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_link', models.TextField(verbose_name='Ссылка на публикацию')),
                ('scientist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.scientistinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ScientistLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на профиль')),
                ('short_desc', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('scientist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.scientistinfo')),
            ],
        ),
    ]
