# Generated by Django 4.2.6 on 2023-11-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientistinfo',
            old_name='institute_id',
            new_name='institute',
        ),
    ]
