# Generated by Django 4.2.6 on 2023-12-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_scientistinfo_scientist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, default='None', verbose_name='Информация об институте'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Название института'),
        ),
    ]
