# Generated by Django 4.2.6 on 2023-11-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_institute_id_scientistinfo_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='text',
        ),
        migrations.AddField(
            model_name='grant',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание гранта'),
        ),
        migrations.AddField(
            model_name='grant',
            name='end_doc_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания приёма заявок'),
        ),
        migrations.AddField(
            model_name='grant',
            name='end_result_date',
            field=models.DateTimeField(null=True, verbose_name='Дата подведения итогов'),
        ),
        migrations.AddField(
            model_name='grant',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Название гранта'),
        ),
    ]
