# Generated by Django 4.2.6 on 2023-11-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0002_alter_queue_obj_type'),
        ('info', '0003_remove_grant_text_grant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scientistinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientistinfo',
            name='scientist_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue'),
            preserve_default=False,
        ),
    ]
