# Generated by Django 4.2.6 on 2023-12-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_institute_description_alter_institute_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScientistPublication',
        ),
    ]
