# Generated by Django 4.2.6 on 2023-12-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_scientist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientist',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='future_plans',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='teaching_info',
        ),
    ]
