# Generated by Django 4.2.6 on 2023-11-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок мероприятия')),
                ('text', models.BinaryField(verbose_name='Текст разметки мероприятия')),
                ('tags', models.TextField(verbose_name='Тэги мероприятия')),
                ('begin_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='moderators.queue')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок новости')),
                ('text', models.BinaryField(verbose_name='Текст разметки новости')),
                ('tags', models.TextField(verbose_name='Тэги новости')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
            ],
        ),
    ]
