# Generated by Django 4.2.6 on 2023-11-30 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('moderators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок мероприятия')),
                ('text', models.BinaryField(verbose_name='Текст разметки мероприятия')),
                ('begin_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на новость в телеграм')),
                ('queue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderators.queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок новости')),
                ('text', models.BinaryField(verbose_name='Текст разметки новости')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на новость в телеграм')),
                ('queue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderators.queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.ImageField(upload_to=news.models.Image._img_dir_path, verbose_name='Путь к изображению')),
                ('alt', models.CharField(default='', max_length=400, verbose_name='Краткое описание')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.event')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.grant')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.institute')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('scientist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.scientistinfo')),
            ],
        ),
    ]
