# Generated by Django 4.2.6 on 2023-11-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_id',
            new_name='news',
        ),
    ]
