# Generated by Django 4.2.6 on 2023-11-19 09:05

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_event_id_event_event_rename_news_id_news_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.ImageField(upload_to=news.models.Image._img_dir_path, verbose_name='Путь к изображению')),
                ('alt', models.CharField(default='', max_length=400, verbose_name='Краткое описание')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.event')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
