# Generated by Django 4.2.6 on 2023-11-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_institute_id_scientistinfo_institute'),
        ('news', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.grant'),
        ),
        migrations.AddField(
            model_name='image',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.institute'),
        ),
        migrations.AddField(
            model_name='image',
            name='scientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.scientistinfo'),
        ),
    ]
